import { StockCardProps } from '../components/StockCardEditText';

export const mockStocks: StockCardProps[] = [
  {
    symbol: 'ICICIBANK',
    name: 'ICICIBANK',
    exchange: 'NSE',
    price: 1430.8,
    change: 868.4,
    changePercent: 0.39,
    volume: '107.38k',
    volumeChange: 0.39,
    newsCount: 2,
    attachmentCount: 1,
  },
  {
    symbol: 'SBIN',
    name: 'SBIN',
    exchange: 'NSE | EQ',
    price: 811,
    change: -868.4,
    changePercent: -0.39,
    volume: '107.38k',
    volumeChange: 0.39,
  },
  {
    symbol: 'RELIANCE',
    name: 'RELIANCE',
    exchange: 'NSE',
    price: 2456.75,
    change: 45.3,
    changePercent: 1.88,
    volume: '245.67k',
    volumeChange: 2.15,
    newsCount: 5,
    attachmentCount: 2,
  },
  {
    symbol: 'TCS',
    name: 'TCS',
    exchange: 'NSE | EQ',
    price: 3589.9,
    change: -23.1,
    changePercent: -0.64,
    volume: '89.45k',
    volumeChange: -1.23,
    newsCount: 3,
  },
  {
    symbol: 'HDFCBANK',
    name: 'HDFCBANK',
    exchange: 'NSE',
    price: 1678.25,
    change: 12.85,
    changePercent: 0.77,
    volume: '198.32k',
    volumeChange: 0.56,
    newsCount: 1,
    attachmentCount: 3,
  },
  {
    symbol: 'INFY',
    name: 'INFY',
    exchange: 'NSE | EQ',
    price: 1523.4,
    change: -8.6,
    changePercent: -0.56,
    volume: '156.78k',
    volumeChange: 1.89,
  },
  {
    symbol: 'HINDUNILVR',
    name: 'HINDUNILVR',
    exchange: 'NSE',
    price: 2734.5,
    change: 34.2,
    changePercent: 1.27,
    volume: '67.89k',
    volumeChange: -0.45,
    newsCount: 2,
  },
  {
    symbol: 'BHARTIARTL',
    name: 'BHARTIARTL',
    exchange: 'NSE | EQ',
    price: 1289.3,
    change: 15.75,
    changePercent: 1.24,
    volume: '234.56k',
    volumeChange: 3.21,
    newsCount: 4,
    attachmentCount: 1,
  },
  {
    symbol: 'ITC',
    name: 'ITC',
    exchange: 'NSE',
    price: 456.8,
    change: -5.2,
    changePercent: -1.13,
    volume: '345.67k',
    volumeChange: 0.78,
  },
  {
    symbol: 'KOTAKBANK',
    name: 'KOTAKBANK',
    exchange: 'NSE | EQ',
    price: 1845.6,
    change: 28.4,
    changePercent: 1.56,
    volume: '123.45k',
    volumeChange: 1.12,
    newsCount: 1,
  },
  {
    symbol: 'LT',
    name: 'LT',
    exchange: 'NSE',
    price: 3267.9,
    change: -42.15,
    changePercent: -1.27,
    volume: '87.65k',
    volumeChange: -2.34,
    attachmentCount: 2,
  },
  {
    symbol: 'AXISBANK',
    name: 'AXISBANK',
    exchange: 'NSE | EQ',
    price: 1067.45,
    change: 9.85,
    changePercent: 0.93,
    volume: '187.23k',
    volumeChange: 0.67,
    newsCount: 3,
  },
  {
    symbol: 'WIPRO',
    name: 'WIPRO',
    exchange: 'NSE',
    price: 567.3,
    change: -12.45,
    changePercent: -2.15,
    volume: '145.89k',
    volumeChange: 1.45,
  },
  {
    symbol: 'ASIANPAINT',
    name: 'ASIANPAINT',
    exchange: 'NSE | EQ',
    price: 3123.75,
    change: 56.8,
    changePercent: 1.85,
    volume: '56.78k',
    volumeChange: -0.89,
    newsCount: 2,
    attachmentCount: 1,
  },
  {
    symbol: 'MARUTI',
    name: 'MARUTI',
    exchange: 'NSE',
    price: 10234.6,
    change: -123.4,
    changePercent: -1.19,
    volume: '34.56k',
    volumeChange: -1.67,
  },
  {
    symbol: 'SUNPHARMA',
    name: 'SUNPHARMA',
    exchange: 'NSE | EQ',
    price: 1456.25,
    change: 18.9,
    changePercent: 1.32,
    volume: '98.76k',
    volumeChange: 2.34,
    newsCount: 1,
  },
  {
    symbol: 'TITAN',
    name: 'TITAN',
    exchange: 'NSE',
    price: 3456.8,
    change: 45.6,
    changePercent: 1.34,
    volume: '76.54k',
    volumeChange: 0.98,
    attachmentCount: 3,
  },
  {
    symbol: 'BAJFINANCE',
    name: 'BAJFINANCE',
    exchange: 'NSE | EQ',
    price: 7234.9,
    change: -89.7,
    changePercent: -1.23,
    volume: '45.67k',
    volumeChange: -0.56,
    newsCount: 4,
  },
  {
    symbol: 'TECHM',
    name: 'TECHM',
    exchange: 'NSE',
    price: 1678.4,
    change: 23.5,
    changePercent: 1.42,
    volume: '112.34k',
    volumeChange: 1.78,
  },
  {
    symbol: 'ULTRACEMCO',
    name: 'ULTRACEMCO',
    exchange: 'NSE | EQ',
    price: 8956.75,
    change: -67.25,
    changePercent: -0.75,
    volume: '23.45k',
    volumeChange: -1.23,
    newsCount: 1,
    attachmentCount: 1,
  },
  {
    symbol: 'NESTLEIND',
    name: 'NESTLEIND',
    exchange: 'NSE',
    price: 23456.9,
    change: 234.6,
    changePercent: 1.01,
    volume: '12.34k',
    volumeChange: 0.45,
  },
  {
    symbol: 'POWERGRID',
    name: 'POWERGRID',
    exchange: 'NSE | EQ',
    price: 289.45,
    change: -3.65,
    changePercent: -1.25,
    volume: '456.78k',
    volumeChange: 2.89,
    newsCount: 2,
  },
  {
    symbol: 'ONGC',
    name: 'ONGC',
    exchange: 'NSE',
    price: 234.8,
    change: 5.4,
    changePercent: 2.35,
    volume: '567.89k',
    volumeChange: 3.45,
    attachmentCount: 2,
  },
  {
    symbol: 'NTPC',
    name: 'NTPC',
    exchange: 'NSE | EQ',
    price: 345.6,
    change: -2.3,
    changePercent: -0.66,
    volume: '345.67k',
    volumeChange: -0.78,
  },
  {
    symbol: 'TATAMOTORS',
    name: 'TATAMOTORS',
    exchange: 'NSE',
    price: 789.3,
    change: 12.45,
    changePercent: 1.6,
    volume: '234.56k',
    volumeChange: 1.23,
    newsCount: 3,
  },
  {
    symbol: 'TATASTEEL',
    name: 'TATASTEEL',
    exchange: 'NSE | EQ',
    price: 145.6,
    change: -1.8,
    changePercent: -1.22,
    volume: '456.78k',
    volumeChange: 0.89,
  },
  {
    symbol: 'ADANIPORTS',
    name: 'ADANIPORTS',
    exchange: 'NSE',
    price: 1234.5,
    change: 34.2,
    changePercent: 2.85,
    volume: '89.45k',
    volumeChange: 4.56,
    newsCount: 5,
    attachmentCount: 2,
  },
  {
    symbol: 'CIPLA',
    name: 'CIPLA',
    exchange: 'NSE | EQ',
    price: 1456.75,
    change: -15.3,
    changePercent: -1.04,
    volume: '67.89k',
    volumeChange: -1.45,
  },
  {
    symbol: 'DRREDDY',
    name: 'DRREDDY',
    exchange: 'NSE',
    price: 5678.9,
    change: 78.4,
    changePercent: 1.4,
    volume: '34.56k',
    volumeChange: 0.67,
    newsCount: 2,
  },
  {
    symbol: 'GRASIM',
    name: 'GRASIM',
    exchange: 'NSE | EQ',
    price: 2345.6,
    change: -28.9,
    changePercent: -1.22,
    volume: '45.67k',
    volumeChange: -0.89,
    attachmentCount: 1,
  },
];
